/**
 * This file was automatically generated by GraphQL Nexus
 * Do not make changes to this file directly
 */

import * as Context from "./context"
import { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    date<FieldName extends string>(fieldName: FieldName, opts?: core.ScalarInputFieldConfig<core.GetGen3<"inputTypes", TypeName, FieldName>>): void // "Date";
    datetime<FieldName extends string>(fieldName: FieldName, opts?: core.ScalarInputFieldConfig<core.GetGen3<"inputTypes", TypeName, FieldName>>): void // "DateTime";
    upload<FieldName extends string>(fieldName: FieldName, opts?: core.ScalarInputFieldConfig<core.GetGen3<"inputTypes", TypeName, FieldName>>): void // "Upload";
    password<FieldName extends string>(fieldName: FieldName, opts?: core.ScalarInputFieldConfig<core.GetGen3<"inputTypes", TypeName, FieldName>>): void // "Password";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Date";
    datetime<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
    upload<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Upload";
    password<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Password";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  CoordsFilterInput: { // input type
    gte: number; // Float!
    lte: number; // Float!
  }
  CourtsFilterInput: { // input type
    latitude: NexusGenInputs['CoordsFilterInput']; // CoordsFilterInput!
    longitude: NexusGenInputs['CoordsFilterInput']; // CoordsFilterInput!
  }
  CreateCourtInput: { // input type
    address: string; // String!
    courtType: NexusGenEnums['CourtTypeEnum'][]; // [CourtTypeEnum!]!
    name: string; // String!
    numberOfCourts?: number | null; // Int
    phone?: string | null; // String
    suggestedCourtId: string; // ID!
    timeZone: string; // String!
  }
  CreateSessionInput: { // input type
    courtId: string; // ID!
    end: any; // DateTime!
    start: any; // DateTime!
  }
  DeleteSuggestedCourtInput: { // input type
    suggestedCourtId: string; // ID!
  }
  JoinUnjoinSessionInput: { // input type
    sessionId: string; // ID!
  }
  LoginInput: { // input type
    password: string; // String!
    username: string; // String!
  }
  SessionsFilterInput: { // input type
    latitude: NexusGenInputs['CoordsFilterInput']; // CoordsFilterInput!
    longitude: NexusGenInputs['CoordsFilterInput']; // CoordsFilterInput!
  }
  SignUpInput: { // input type
    avatar?: any | null; // Upload
    confirmPassword: any; // Password!
    fullName: string; // String!
    password: any; // Password!
    username: string; // String!
  }
  SuggestCourtInput: { // input type
    city: string; // String!
    name: string; // String!
    state: string; // String!
    street: string; // String!
    timeZone: string; // String!
    zipCode: string; // String!
  }
  UpdateSessionInput: { // input type
    end?: any | null; // DateTime
    sessionId: string; // ID!
    start?: any | null; // DateTime
  }
  UpdateUserInput: { // input type
    avatar?: any | null; // Upload
    fullName?: string | null; // String
    userId: string; // ID!
    username?: string | null; // String
  }
}

export interface NexusGenEnums {
  CourtTypeEnum: "Indoor" | "Outdoor"
}

export interface NexusGenRootTypes {
  Address: { // root type
    city: string; // String!
    country: string; // String!
    state: string; // String!
    street: string; // String!
    streetNumber: string; // String!
    timeZone: string; // String!
    zipCode: string; // String!
  }
  AuthPayload: { // root type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Coords: { // root type
    latitude: number; // Float!
    longitude: number; // Float!
  }
  Court: { // root type
    address: NexusGenRootTypes['Address']; // Address!
    coords: NexusGenRootTypes['Coords']; // Coords!
    id: string; // ID!
    name: string; // String!
    numberOfCourts?: string | null; // String
    phone?: string | null; // String
    type: NexusGenEnums['CourtTypeEnum'][]; // [CourtTypeEnum!]!
  }
  Mutation: {};
  Query: {};
  Session: { // root type
    attending: NexusGenRootTypes['User'][]; // [User!]!
    coords: NexusGenRootTypes['Coords']; // Coords!
    court: NexusGenRootTypes['Court']; // Court!
    createdBy: NexusGenRootTypes['User']; // User!
    end: any; // DateTime!
    id: string; // ID!
    start: any; // DateTime!
    timeZone: string; // String!
  }
  SuggestedCourt: { // root type
    city: string; // String!
    id: string; // ID!
    name: string; // String!
    state: string; // String!
    street: string; // String!
    timeZone: string; // String!
    zipCode: string; // String!
  }
  User: { // root type
    avatarUrl?: string | null; // String
    fullName: string; // String!
    id: string; // ID!
    username: string; // String!
  }
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  ID: string;
  Date: Date;
  DateTime: DateTime;
  Password: any;
  Upload: any;
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  CoordsFilterInput: NexusGenInputs['CoordsFilterInput'];
  CourtsFilterInput: NexusGenInputs['CourtsFilterInput'];
  CreateCourtInput: NexusGenInputs['CreateCourtInput'];
  CreateSessionInput: NexusGenInputs['CreateSessionInput'];
  DeleteSuggestedCourtInput: NexusGenInputs['DeleteSuggestedCourtInput'];
  JoinUnjoinSessionInput: NexusGenInputs['JoinUnjoinSessionInput'];
  LoginInput: NexusGenInputs['LoginInput'];
  SessionsFilterInput: NexusGenInputs['SessionsFilterInput'];
  SignUpInput: NexusGenInputs['SignUpInput'];
  SuggestCourtInput: NexusGenInputs['SuggestCourtInput'];
  UpdateSessionInput: NexusGenInputs['UpdateSessionInput'];
  UpdateUserInput: NexusGenInputs['UpdateUserInput'];
  CourtTypeEnum: NexusGenEnums['CourtTypeEnum'];
}

export interface NexusGenFieldTypes {
  Address: { // field return type
    city: string; // String!
    country: string; // String!
    formattedAddress: string; // String!
    state: string; // String!
    street: string; // String!
    streetNumber: string; // String!
    timeZone: string; // String!
    zipCode: string; // String!
  }
  AuthPayload: { // field return type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Coords: { // field return type
    latitude: number; // Float!
    longitude: number; // Float!
  }
  Court: { // field return type
    address: NexusGenRootTypes['Address']; // Address!
    coords: NexusGenRootTypes['Coords']; // Coords!
    id: string; // ID!
    name: string; // String!
    numberOfCourts: string | null; // String
    phone: string | null; // String
    type: NexusGenEnums['CourtTypeEnum'][]; // [CourtTypeEnum!]!
  }
  Mutation: { // field return type
    adminLogin: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    createCourt: NexusGenRootTypes['Court']; // Court!
    createSession: NexusGenRootTypes['Session']; // Session!
    deleteSuggestedCourt: boolean; // Boolean!
    joinSession: NexusGenRootTypes['Session']; // Session!
    login: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    logout: boolean; // Boolean!
    signup: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    suggestCourt: NexusGenRootTypes['SuggestedCourt']; // SuggestedCourt!
    unjoinSession: NexusGenRootTypes['Session']; // Session!
    updateSession: NexusGenRootTypes['Session']; // Session!
    updateUser: NexusGenRootTypes['User']; // User!
  }
  Query: { // field return type
    courts: NexusGenRootTypes['Court'][]; // [Court!]!
    sessions: NexusGenRootTypes['Session'][]; // [Session!]!
    suggestedCourts: NexusGenRootTypes['SuggestedCourt'][]; // [SuggestedCourt!]!
  }
  Session: { // field return type
    attending: NexusGenRootTypes['User'][]; // [User!]!
    coords: NexusGenRootTypes['Coords']; // Coords!
    court: NexusGenRootTypes['Court']; // Court!
    createdBy: NexusGenRootTypes['User']; // User!
    date: string; // String!
    end: any; // DateTime!
    id: string; // ID!
    numberAttending: number; // Int!
    start: any; // DateTime!
    times: string; // String!
    timeZone: string; // String!
  }
  SuggestedCourt: { // field return type
    city: string; // String!
    id: string; // ID!
    name: string; // String!
    state: string; // String!
    street: string; // String!
    timeZone: string; // String!
    zipCode: string; // String!
  }
  User: { // field return type
    avatarUrl: string | null; // String
    fullName: string; // String!
    id: string; // ID!
    username: string; // String!
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    adminLogin: { // args
      input: NexusGenInputs['LoginInput']; // LoginInput!
    }
    createCourt: { // args
      input: NexusGenInputs['CreateCourtInput']; // CreateCourtInput!
    }
    createSession: { // args
      input: NexusGenInputs['CreateSessionInput']; // CreateSessionInput!
    }
    deleteSuggestedCourt: { // args
      input: NexusGenInputs['DeleteSuggestedCourtInput']; // DeleteSuggestedCourtInput!
    }
    joinSession: { // args
      input: NexusGenInputs['JoinUnjoinSessionInput']; // JoinUnjoinSessionInput!
    }
    login: { // args
      input: NexusGenInputs['LoginInput']; // LoginInput!
    }
    signup: { // args
      input: NexusGenInputs['SignUpInput']; // SignUpInput!
    }
    suggestCourt: { // args
      input: NexusGenInputs['SuggestCourtInput']; // SuggestCourtInput!
    }
    unjoinSession: { // args
      input: NexusGenInputs['JoinUnjoinSessionInput']; // JoinUnjoinSessionInput!
    }
    updateSession: { // args
      input: NexusGenInputs['UpdateSessionInput']; // UpdateSessionInput!
    }
    updateUser: { // args
      input: NexusGenInputs['UpdateUserInput']; // UpdateUserInput!
    }
  }
  Query: {
    courts: { // args
      where?: NexusGenInputs['CourtsFilterInput'] | null; // CourtsFilterInput
    }
    sessions: { // args
      where?: NexusGenInputs['SessionsFilterInput'] | null; // SessionsFilterInput
    }
  }
}

export interface NexusGenAbstractResolveReturnTypes {
}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames = "Address" | "AuthPayload" | "Coords" | "Court" | "Mutation" | "Query" | "Session" | "SuggestedCourt" | "User";

export type NexusGenInputNames = "CoordsFilterInput" | "CourtsFilterInput" | "CreateCourtInput" | "CreateSessionInput" | "DeleteSuggestedCourtInput" | "JoinUnjoinSessionInput" | "LoginInput" | "SessionsFilterInput" | "SignUpInput" | "SuggestCourtInput" | "UpdateSessionInput" | "UpdateUserInput";

export type NexusGenEnumNames = "CourtTypeEnum";

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = "Boolean" | "Date" | "DateTime" | "Float" | "ID" | "Int" | "Password" | "String" | "Upload";

export type NexusGenUnionNames = never;

export interface NexusGenTypes {
  context: Context.Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
}